const amazon = 'https://amzn.eu/d/01feguzW';
const collections = [
 { title:'Klassischer Mix', image:'klassischer-mix.png', alt:'Zehn SGS Jungen-Boxershorts: vier schwarze, drei blaue und drei graue', colors:['#191b1f','#244b7c','#858386'], description:'4 × Schwarz · 3 × Blau · 3 × Grau' },
 { title:'Bunter Mix', image:'bunter-mix.jpg', alt:'Zehn SGS Jungen-Boxershorts: je zwei in Bordeauxrot, Petrol, Blau, Grau und Hellblau', colors:['#a83145','#43818a','#244b7c','#858386','#b9e0ea'], description:'Je 2 × Bordeauxrot, Petrol, Blau, Grau und Hellblau' },
 { title:'Ganz in Schwarz', image:'schwarz.png', alt:'Zehn schwarze SGS Jungen-Boxershorts', colors:['#191b1f'], description:'10 × Schwarz. Einfach klassisch.' },
];
function Brand() { return <a href="#start" className="brand" aria-label="SGS Junior – zur Startseite"><span className="brand-image"><img src="/images/sgs-logo.jpg" alt="SGS" width="2048" height="1280" /></span><span className="brand-junior">Junior</span></a>; }
function AmazonLink({children,className=''}:{children:React.ReactNode;className?:string}) { return <a href={amazon} target="_blank" rel="noopener noreferrer" className={className}>{children}<span aria-hidden="true">↗</span><span className="sr-only"> (Amazon, öffnet in einem neuen Tab)</span></a>; }
export default function Home() { return <>
 <a className="skip-link" href="#inhalt">Zum Inhalt springen</a>
 <div className="announcement">JUNGEN-UNTERWÄSCHE IM 10ER-PACK <span aria-hidden="true">·</span> JETZT AUF AMAZON</div>
 <header id="start" className="site-header"><div className="header-inner"><Brand/><nav aria-label="Hauptnavigation"><a href="#kollektion">Kollektion</a><a href="#details">Material & Passform</a></nav><AmazonLink className="header-amazon">Auf Amazon kaufen</AmazonLink></div></header>
 <main id="inhalt">
 <section className="hero" aria-labelledby="hero-title"><div className="hero-inner">
 <div className="hero-copy"><p className="eyebrow">HALLO, SGS JUNIOR</p><h1 id="hero-title">Für kleine Helden.<br/><span>Für jeden Tag.</span></h1><p className="hero-description">Bequeme Boxershorts für Jungen – aus weicher, atmungsaktiver Baumwolle mit Elasthan. Für Schule, Freizeit und alles, was der Tag bringt.</p><div className="hero-actions"><AmazonLink className="button button-primary">Jetzt auf Amazon kaufen</AmazonLink><a className="text-link" href="#kollektion">Kollektion entdecken <span aria-hidden="true">↓</span></a></div></div>
 <div className="hero-visual"><span className="accent-rays rays-top" aria-hidden="true"/><div className="hero-photo"><div className="pack-photo"><img src="/images/bunter-mix.jpg" alt="SGS Junior: zehn bunte Boxershorts für Jungen mit schwarzem Markenbund" width="1537" height="1023" fetchPriority="high"/></div></div><div className="hero-caption"><span>Ein Pack. Viele Lieblingsfarben.</span><span className="pack-label">10er-Pack</span></div><span className="accent-rays rays-bottom" aria-hidden="true"/></div>
 </div></section>
 <div className="product-facts" aria-label="Produktmerkmale"><p><strong>95 %</strong> Baumwolle</p><p><strong>5 %</strong> Elasthan</p><p><strong>10</strong> Boxershorts pro Pack</p><p><strong>98–176</strong> EU-Kindergrößen</p></div>
 <section id="kollektion" className="collection section-wrap" aria-labelledby="collection-title"><div className="section-heading"><p className="eyebrow">UNSERE KOLLEKTION</p><h2 id="collection-title">Lieblingsfarben für jeden Tag.</h2></div><div className="collection-grid">{collections.map(item=><article className="collection-card" key={item.title}><div className="collection-photo"><div className="pack-photo"><img src={'/images/'+item.image} alt={item.alt} width="1537" height="1023" loading="lazy"/></div></div><div className="card-content"><div className="card-title-row"><h3>{item.title}</h3><div className="swatches" aria-hidden="true">{item.colors.map(color=><i key={color} style={{backgroundColor:color}}/>)}</div></div><p className="card-type">Jungen-Boxershorts · 10er-Pack</p><p className="card-description">{item.description}</p><AmazonLink className="text-link">Auf Amazon ansehen</AmazonLink></div></article>)}</div><p className="availability-note">Verfügbare Modelle, Größen und aktuelle Preise findest du auf Amazon.</p></section>
 <section id="details" className="details-section" aria-labelledby="details-title"><div className="section-wrap details-inner"><div className="details-intro"><p className="eyebrow">MATERIAL & PASSFORM</p><h2 id="details-title">Bequem, wenn der Alltag in Bewegung ist.</h2><p>Vom ersten Klingeln bis zum letzten Abenteuer: Unterwäsche, die sich angenehm anfühlt und Platz zum Spielen lässt.</p><AmazonLink className="text-link">Alle Produktdetails auf Amazon</AmazonLink></div><div className="details-grid"><article><span className="detail-number">01</span><h3>Weich & atmungsaktiv</h3><p>95 % Baumwolle und 5 % Elasthan verbinden ein angenehmes Hautgefühl mit elastischem Sitz.</p></article><article><span className="detail-number">02</span><h3>Platz für Bewegung</h3><p>Die körpergerechte Passform bietet Bewegungsfreiheit beim Spielen, Toben und Sport.</p></article><article><span className="detail-number">03</span><h3>Einfach im Alltag</h3><p>Das praktische 10er-Pack erleichtert den täglichen Wechsel. Für die Maschinenwäsche geeignet.</p></article><article><span className="detail-number">04</span><h3>Die passende Größe</h3><p>EU-Kindergrößen von 98 bis 176. Die Größentabelle auf Amazon hilft dir bei der Auswahl.</p></article></div></div></section>
 <section className="closing" aria-labelledby="closing-title"><p className="eyebrow">SGS JUNIOR</p><h2 id="closing-title">Bereit für den nächsten Tag?</h2><p>Entdecke SGS Jungen-Boxershorts auf Amazon.</p><AmazonLink className="button button-white">Jetzt auf Amazon kaufen</AmazonLink></section>
 </main><footer className="site-footer"><div className="footer-inner"><Brand/><p>Jungen-Unterwäsche für jeden Tag.</p><AmazonLink className="footer-link">Bestellung & Kundenservice über Amazon</AmazonLink></div><div className="footer-bottom"><span>© {new Date().getFullYear()} SGS Junior</span><a href="#start">Zurück nach oben ↑</a></div></footer>
 </>; }
